> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [4]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tanu1007/numpy-array-operations


'https://jovian.ai/tanu1007/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.array
function2 = np.flatten
function3 = np.stack
function4 = np.array_split
function5 = np.resize

## Function 1 - np.array([elements])

Create an array

In [6]:
# Example 1 - working (change this)
arr1 = np.array([1.,2.,3.,4.,5.])
arr1

array([1., 2., 3., 4., 5.])

created an 1D array with shape (1,5)

In [8]:
# Example 2 - working
arr2 = np.array([[6.,7.,8.,9.,10.],
         [11.,12.,13.,14.,15.]])
arr2

array([[ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

Created 2D array with shape (2,5).

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = np.array([[1,2,3,4,5],
                 [A,B,C,D,E,F,G]])
arr3

NameError: ignored

Problem: we cant make a matrix with alphabets and numbers
Solution: Don't use alphabets for a matrix

Some closing comments about when to use this function.

We use it to make arrays for array manipulation to later perform

In [13]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tanu1007/numpy-array-operations


'https://jovian.ai/tanu1007/numpy-array-operations'

## Function 2 - np.flatten()

Return a copy of the array collapsed into one dimension.

In [16]:
# Example 1 - working
arr2_flattened = arr2.flatten()
arr2_flattened

array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.])

As we knew arr2 is a 2D array..and np.flatten made it into 1D by flattening it.

In [19]:
# Example 2 - working
arr3 = np.array([[[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]],
                 [[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]],
                 [[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]]])
arr3_flattened = arr3.flatten()
print(arr3_flattened)
print("Shape of arr3:",arr3.shape)
print("Shape of flattened array",arr3_flattened.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  1  2  3  4  5  6  7  8  9
 10 11 12 13 14 15  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Shape of arr3: (3, 3, 5)
Shape of flattened array (45,)


arr3 was a 3D array of (3,3,5) which converted to arr3_flattened (45,1)

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = np.array([[[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]],
                 [[1,2,3,4,5],
                  [6,7,8,9],
                  [11,12,13,14,15]],
                 [[1,2,3,4,5],
                  [6,7,8,9,10]]])
arr3_flattened = arr3.flatten(['D'])
print(arr3_flattened)

ValueError: ignored

Problem: The order passed into ndarray.flatten([]) has to be one of the (A,K,C,F)
The meaning of this letter are explained in documentation of numpy

Solution: Choose alphabet from (A,K,C,F) else leave a blank for default

Some closing comments about when to use this function.

In [25]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tanu1007/numpy-array-operations


'https://jovian.ai/tanu1007/numpy-array-operations'

## Function 3 - np.stack()

Join a sequence of arrays along a new axis.

In [30]:
# Example 1 - working
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,0])

a3 = np.stack((a1,a2),axis=1)
print(a3)
print(a3.shape)

[[1 6]
 [2 7]
 [3 8]
 [4 9]
 [5 0]]
(5, 2)


merged a1 and a2 and changed it's shape to 5,2 to 2,5

In [34]:
# Example 2 - working
a1 = np.array([[6,7,8,9,10],
         [11,12,13,14,15]])
a2 = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])

a3 = np.stack((a1,a2))
print(a3)
print(a3.shape)

[[[ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
(2, 2, 5)


a1 of shape: (2,5)
a2 of shape: (2,5)

a3 into 3D array of shape(2,2,5)

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
a1 = np.array([[6.,7.,8.,9.,10.],
         [11.,12.,13.,14.,15.]])
a2 = np.array([[[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]],
                 [[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]],
                 [[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15]]])

a3 = np.stack((a1,a2),axis=1)
print(a3)
print(a3.shape)

ValueError: ignored

Problem: Array must have same shapes
Solution: try reshaping your arrays

Some closing comments about when to use this function.

In [36]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tanu1007/numpy-array-operations


'https://jovian.ai/tanu1007/numpy-array-operations'

## Function 4 - np.array_split()

Split an array into multiple sub-arrays.

numpy.array_split(ary, indices_or_sections, axis=0)

In [37]:
# Example 1 - working
x = x = np.arange(9.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

It splits array of size 9 into 3 equal parts

In [38]:
# Example 2 - working
x = x = np.arange(7.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.])]

splits array of size into possible equal parts and then sets accordingly



In [39]:
# Example 3 - breaking (to illustrate when it breaks)
x = x = np.arange(7.0)
np.array_split(x, 0)

ValueError: ignored

The parameter indices should be greater than zero in order to work.

This function is mainly used to extract required information through splitting which makes work easy

In [40]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tanu1007/numpy-array-operations


'https://jovian.ai/tanu1007/numpy-array-operations'

## Function 5 - np.resize()

Return a new array with the specified shape.

In [49]:
# Example 1 - working
x = x = np.arange(9.0)
y = np.resize(x,(3,3))
print(x)
print()
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


shape of x: (1,9)
shape of y: (3,3)

In [48]:
# Example 2 - working
x = x = np.arange(16).reshape(4,4)
y = np.resize(x,(2,8))
print(x)
print()
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


shape of x: (4,4)
shape of y: (2,8)

In [55]:
# Example 3 - breaking (to illustrate when it breaks)
x = x = np.arange(16).reshape(4,4)
y = np.resize(x,(2,2 0))
print(x)
print()
print(y)

SyntaxError: ignored

Problem: it's breaks only when theres a syntax error

If the new array has more rows, it will repeat the data in the original array but not raise the error.

In [56]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tanu1007/numpy-array-operations


'https://jovian.ai/tanu1007/numpy-array-operations'

## Conclusion

This notebook covers all the main functions of numpy which is widely and frequently used in all the applications which includes arrays. This all functions are integral part of any big algorithms which we see and build. Hence proper understanding and working of these funcions is mandontary and required

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [57]:
jovian.commit(his notebook covers all the main functions of numpy which is widely and frequently used in all the applications which includes arrays. This all functions are integral part of any big algorithms which we see and build. Hence proper understanding and working of these funcions is mandontary and requi)

SyntaxError: ignored